/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sort */

#ifndef _Included_Sort
#define _Included_Sort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sort
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT void JNICALL Java_Sort_sort
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
